collections:
  # see https://galaxy.ansible.com/cloud/terraform
  - name: cloud.terraform
    version: 4.0.0
  # see https://galaxy.ansible.com/ansible/windows
  - name: ansible.windows
    version: 3.2.0
  # see https://galaxy.ansible.com/chocolatey/chocolatey
  - name: chocolatey.chocolatey
    version: 1.5.3
  # see https://galaxy.ansible.com/community/general
  - name: community.general
    version: 11.3.0
  # see https://galaxy.ansible.com/community/windows
  - name: community.windows
    version: 3.0.1
