# see https://launchpad.net/ubuntu/+archivemirrors
# see https://launchpad.net/ubuntu/+mirror/mirrors.up.pt-archive
# see https://launchpad.net/ubuntu/+mirror/ftp.uni-stuttgart.de-archive
# wsl_ubuntu_apt_sources_url: http://mirrors.up.pt/ubuntu
wsl_ubuntu_apt_sources_url: http://ftp.uni-stuttgart.de/ubuntu
